### ISSUE TITLE
Do I need an apartment lease contract to apply for Blue Card, get a bank account, etc?

### ISSUE THREAD

**Issue by osym** [azproduction/relocating-to-berlin#18]
Hi guys,

As I understood everybody needs an address to present it everywhere where it is needed. Do I have to prove that I actually live there? Do I need to show a lease contract? Is it okay to rent an apartment on AirBnB without written agreement?

**Comment by azproduction** [comment]
Hey,

Usually when you are applying for a Blue Card you are not renting anything, because you are not sure will you get BC or not.

> As I understood everybody needs an address to present it everywhere where it is needed. 

Usually it is fine to put just the address of the employer (office address). I did that.

> Do I need to show a lease contract?

As far as I can remember, they did not ask for it (not a requirement for Blue Card **while you are outside of Germany**). However paper contract will be **mandatory for a registration** which is a pre requirement for a Blue Card, when you are **inside of Germany**. So basically Blue Card consists of 2 parts, for the very first one it is not required to have an real apartment. 

> Is it okay to rent an apartment on AirBnB without written agreement?

After getting the 3 months visa, I booked an apartment on AirBnB. Before booking I asked the landlord whether he can issue a rent contract in some form. He said yes, and temporary contract was enough for a Blue Card. After getting permanent place (+2 months after getting BlueCard) I just changed address. So the landlord must **provide you a paper contract** (even for 1-2 months) in order to get registration and then a BlueCard.
